#!/bin/bash

requirements=(build-essential libpng-dev libcairo2-dev libpango1.0-dev libglib2.0-dev libgtk2.0-dev libswscale-dev libavcodec-dev libavformat-dev libgtk-3-dev)

sudo apt-get install ${requirements[*]}
